### ISSUE TITLE
Error with avprobe_installed

### ISSUE THREAD

**Issue by dohliam** [Pat-Carter/stream2chromecast#1]
I got the following error when trying to run stream2chromecast:

    avconv version 9.16-6:9.16-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
      built on Aug 10 2014 18:16:02 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
    Traceback (most recent call last):
      File "./stream2chromecast.py", line 446, in <module>
        run()
      File "./stream2chromecast.py", line 442, in run
        play(arg1)        
      File "./stream2chromecast.py", line 320, in play
        transcoder_cmd, probe_cmd = get_transcoder_cmds()
      File "./stream2chromecast.py", line 124, in get_transcoder_cmds
        elif avprobe_installed:
    NameError: global name 'avprobe_installed' is not defined

I looked at line 124 in stream2chromecast.py which looks like this:

            elif avprobe_installed:

Since `avprobe_installed` is not defined anywhere, but `avconv_installed` is defined a few lines above, I figured it was a typo, and changed line 124 to the following:

            elif avconv_installed:

After this, everything worked! Streaming to the chromecast works great now.

Let me know if you'd be open to me opening a pull request to correct this.

**Comment by Pat-Carter** [comment]
Thanks! Yes, please open the pull request.
