### ISSUE TITLE
Ubuntu 16.04 Connection Refused

### ISSUE THREAD

**Issue by kyleamadio** [Pat-Carter/stream2chromecast#11]
I can cast from my Android phone and  Chrome browser successful, however cannot from stream2chromecast 

stream2chromecast -devicename Chromecast18 DSC_6643.MOV
searching the network for: Chromecast18
Traceback (most recent call last):
  File "/usr/bin/stream2chromecast", line 572, in <module>
    run()
  File "/usr/bin/stream2chromecast", line 568, in run
    play(args[0], device_name=device_name, server_port=server_port)        
  File "/usr/bin/stream2chromecast", line 320, in play
    cast = CCMediaController(device_name=device_name)
  File "/opt/stream2chromecast/cc_media_controller.py", line 25, in __init__
    self.host = self.get_device(device_name)
  File "/opt/stream2chromecast/cc_media_controller.py", line 52, in get_device
    host, name = cc_device_finder.find_device(name=device_name)
  File "/opt/stream2chromecast/cc_device_finder.py", line 161, in find_device
    result_map[get_device_name(host)] = host
  File "/opt/stream2chromecast/cc_device_finder.py", line 80, in get_device_name
    conn.request("GET", "/ssdp/device-desc.xml")
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

It will connect if I explicitly enter the ip address of the Chromecast device

stream2chromecast -devicename 192.168.1.138 DSC_6643.MOV
ip_addr: 192.168.1.138 device name: Chromecast18
Playing: /home/xxxxx/Videos/Claires Wedding/video/Disk1/DSC_6643.MOV
OS identifies the mimetype as : video/quicktime
my ip address: 192.168.1.137
URL & content-type:  http://192.168.1.137:44281/home/xxxxx/Videos/Claires+Wedding/video/Disk1/DSC_6643.MOV video/quicktime
loading media...

However it does not actually play the file - just shows the Chromecast symbol. Might be a file format issue - its a quicktime file

waiting for player to finish - press ctrl-c to stop...
done

**Comment by kyleamadio** [comment]
![20160803_105413](https://cloud.githubusercontent.com/assets/1647986/17350402/c174c14e-5969-11e6-9f73-8298b97c0c11.jpg)

**Comment by Pat-Carter** [comment]
Hi, 

The devicename issue should be resolved now. Could you grab the latest version and let me know if it helps, please?

thanks,

Pat

**Comment by kyleamadio** [comment]
Ok will do

**Comment by kyleamadio** [comment]
The discover works now -

stream2chromecast -devicename Chromecast18 Video7.mp4
searching the network for: Chromecast18
found device: Chromecast18
device name: Chromecast18

Playing: /home/xxxxx/Videos/Claires Wedding/YouTube/Video7.mp4
OS identifies the mimetype as : video/mp4
my ip address: 192.168.1.137
URL & content-type: 
http://192.168.1.137:42427/home/kylea/Videos/Claires+Wedding/YouTube/Video7.mp4
video/mp4
loading media...

Seems to start loading on the TV however the actual file does not play.

Kind Regards

Kyle Amadio
Director - Magical Connect Pty Limited
+61 411 707081

**Comment by Pat-Carter** [comment]
It could be that the video is not streamable - not all MP4 files are (they have to be encoded in fragments).

Could you try using the transcode option, please?

stream2chromecast -devicename Chromecast18 -transcode Video7.mp4

cheers,

Pat

**Comment by kyleamadio** [comment]
Ok tried that same effect. So I used handbrake and ffmpeg to move the
"moov atom" same results - connects but no video plays


ffmpeg -i Video7.mp4 -movflags faststart -acodec copy -vcodec copy
output.mp4
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
  configuration: --prefix=/usr --extra-version=1ubuntu2
--build-suffix=-ffmpeg --toolchain=hardened
--libdir=/usr/lib/x86_64-linux-gnu
--incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl
--enable-shared --disable-stripping --disable-decoder=libopenjpeg
--disable-decoder=libschroedinger --enable-avresample --enable-avisynth
--enable-gnutls --enable-ladspa --enable-libass --enable-libbluray
--enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame
--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp
--enable-libschroedinger --enable-libshine --enable-libsnappy
--enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora
--enable-libtwolame --enable-libvorbis --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid
--enable-libzvbi --enable-openal --enable-opengl --enable-x11grab
--enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r
--enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Video7.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-01 09:09:24
  Duration: 00:02:00.66, start: 0.000000, bitrate: 6019 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz,
stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2016-08-01 09:09:24
      handler_name    : Mainconcept MP4 Sound Media Handler
    Stream #0:1(eng): Video: h264 (High) (avc1 / 0x31637661),
yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 5856 kb/s, 59.94 fps,
59.94 tbr, 60k tbn, 119.88 tbc (default)
    Metadata:
      creation_time   : 2016-08-01 09:09:24
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
[mp4 @ 0x10f6220] Codec for stream 0 does not use global headers but
container format requires global headers
[mp4 @ 0x10f6220] Codec for stream 1 does not use global headers but
container format requires global headers
Output #0, mp4, to 'output.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf56.40.101
    Stream #0:0(eng): Video: h264 ([33][0][0][0] / 0x0021), yuv420p,
1280x720 [SAR 1:1 DAR 16:9], q=2-31, 5856 kb/s, 59.94 fps, 59.94 tbr,
60k tbn, 60k tbc (default)
    Metadata:
      creation_time   : 2016-08-01 09:09:24
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz,
stereo, 156 kb/s (default)
    Metadata:
      creation_time   : 2016-08-01 09:09:24
      handler_name    : Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x10f6220] *Starting second pass: moving the moov atom to the
beginning of the file*
frame= 7231 fps=0.0 q=-1.0 Lsize=   88731kB time=00:02:00.66
bitrate=6024.1kbits/s   
video:86251kB audio:2306kB subtitle:0kB other streams:0kB global
headers:0kB muxing overhead: 0.195341%


On 4 Aug 2016 10:26 PM, "Pat Carter" <notifications@github.com
<mailto:notifications@github.com>> wrote:

    It could be that the video is not streamable - not all MP4 files are
    (they have to be encoded in fragments).

    Could you try using the transcode option, please?

    stream2chromecast -devicename Chromecast18 -transcode Video7.mp4

    cheers,

    Pat

    —
    You are receiving this because you authored the thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/Pat-Carter/stream2chromecast/issues/11#issuecomment-237537741>,
    or mute the thread

**Comment by Pat-Carter** [comment]
OK - Do you have any king of firewall running on your PC?

What the script does is to setup an ad-hoc webserver to serve the file to
the Chromecast.

I'm wondering if we've sent the play command to the Chromecast, and it
tries to request it from the PC, but can't get through.

**Comment by kyleamadio** [comment]
Yes I have a firewall - running Ubuntu 64Bit 16.04 - I tried a sample
mp4 file from the web that did stream from the web - so its something
getting in the way



Kind Regards

Kyle Amadio
Director - Magical Connect Pty Limited
+61 411 707081

**Comment by kyleamadio** [comment]
I tailed syslog


Aug  4 23:09:00 kylea-XPS-15-9550 kernel: [ 2012.108856] [UFW BLOCK]
IN=wlp2s0 OUT= MAC=48:e2:44:f6:d6:85:d0:e7:82:c7:62:5d:08:00
*SRC=192.168.1.138* DST=192.168.1.137 LEN=60 TOS=0x00 PREC=0x00 TTL=64
ID=25555 DF PROTO=TCP *SPT=43701 DPT=38931* WINDOW=14600 RES=0x00 SYN
URGP=0

Aug  4 23:09:01 kylea-XPS-15-9550 kernel: [ 2012.453502] [UFW BLOCK]
IN=wlp2s0 OUT= MAC=48:e2:44:f6:d6:85:d0:e7:82:c7:62:5d:08:00
SRC=192.168.1.138 DST=192.168.1.137 LEN=60 TOS=0x00 PREC=0x00 TTL=64
ID=57264 DF PROTO=TCP *SPT=43702 DPT=38931* WINDOW=14600 RES=0x00 SYN
URGP=0

Aug  4 23:09:01 kylea-XPS-15-9550 kernel: [ 2013.172576] [UFW BLOCK]
IN=wlp2s0 OUT= MAC=48:e2:44:f6:d6:85:d0:e7:82:c7:62:5d:08:00
SRC=192.168.1.138 DST=192.168.1.137 LEN=60 TOS=0x00 PREC=0x00 TTL=64
ID=25556 DF PROTO=TCP *SPT=43701 DPT=38931* WINDOW=14600 RES=0x00 SYN
URGP=0

Aug  4 23:09:01 kylea-XPS-15-9550 kernel: [ 2013.354507] [UFW BLOCK]
IN=wlp2s0 OUT= MAC=48:e2:44:f6:d6:85:d0:e7:82:c7:62:5d:08:00
SRC=192.168.1.138 DST=192.168.1.137 LEN=60 TOS=0x00 PREC=0x00 TTL=64
ID=57265 DF PROTO=TCP*SPT=43702 DPT=38931* WINDOW=14600 RES=0x00 SYN URGP=0 



Kind Regards

Kyle Amadio
Director - Magical Connect Pty Limited
+61 411 707081

**Comment by Pat-Carter** [comment]
OK. By default, it sets up the web server to listen for requests from Chromecast on a random port number.

You can use the -port parameter to specify the port that it listens on.

e.g. if you wanted to use port 8765...

./stream2chromecast.py -port 8765 my_video.mp4

Then you would need to open that port on your firewall to allow incoming requests from your Chromecast.

Could you give that a try, please?

**Comment by kyleamadio** [comment]
fixed - it was the firewall


      or, how I got Chromecast to work with Ubuntu
      <http://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwi_253M66fOAhVGkpQKHRLSDqUQFgglMAE&url=http%3A%2F%2Farusahni.net%2Fblog%2F2013%2F08%2Fchromecast-and-ubuntu.html&usg=AFQjCNFV5tqKpgReqQ27kKEqg9wLPFnsvA>

arusahni.net/blog/2013/08/*chromecast*-and-*ubuntu*.html
Aug 25, 2013 - In which I get my /Chromecast/ to play nicely with my
software firewall. ... Using the now-static IP address and your local
/port ranges/, tell ufw to step off! ... /allow/ proto udp from
192.168.1.42 to any /port/ 32768:61000 Rule added.



Kind Regards

Kyle Amadio
Director - Magical Connect Pty Limited
+61 411 707081

**Comment by kyleamadio** [comment]
Yeap - all good now - thanks for your support !



Kind Regards

Kyle Amadio
Director - Magical Connect Pty Limited
+61 411 707081
