### ISSUE TITLE
-status option doenst provide real information about device status

### ISSUE THREAD

**Issue by Vednier** [Pat-Carter/stream2chromecast#17]
To cut in short - if you initiate some playback from another device, like youtube app on android and something like that and then execute stream2chromecast you will get output like that

> searching the network for a Chromecast device
> device name: BedroomTV
> {'host': '192.168.1.106', 'client': ('192.168.1.100', 43530), 'media_status': None, 'receiver_status': None}

Its true that strea2chromecast doesn't play anything on this device, but actual device is busy right now.
Is there any way to show that device is doing something? (like official Google Cast application do).

**Comment by Pat-Carter** [comment]
You're right, the status info displayed is restricted to the Media Player app. The displayed data is just taken from the statuses used by the media controller to work out which messages it can send.

I think it's theoretically possible for the device to be running multiple applications simultaneously, so what I've done is to add another item to the status info which lists the current applications, and their displayable status, if they provide it.

So, if you grab the latest version, run Youtube on it and the run -status, it should now return something like:-

{'applications': [{'statusText': u'YouTube TV', 'displayName': u'YouTube', 'appId': u'233637DE'}], 'host': '192.168.1.10', 'client': ('192.168.1.21', 38212), 'media_status': None, 'receiver_status': None}

I hope this helps.

**Comment by Vednier** [comment]
Thanks, update just arrived to Ubuntu WebUpd repository, so i tested it.
Indeed, its now shows "application" running. Backdrop is "idle" screensaver.
{'applications': [{'statusText': u'', 'displayName': u'Backdrop', 'appId': u'E8C28D3C'}], 'host': '192.168.1.103', 'client': ('192.168.1.100', 42430), 'media_status': None, 'receiver_status': None}
