### ISSUE TITLE
Command should use stream2chromecast and not stream2chromecast.py ?

### ISSUE THREAD

**Issue by khurshid-alam** [Pat-Carter/stream2chromecast#24]
The python script is already using shebang. So invoking `/usr/binstream2chromecast`  should be sufficient and the script can be renamed without `.py`. No?

**Comment by Pat-Carter** [comment]
Hi,

The file extension ".py" isn't (generally) used to associate the script with the python interpreter on Unix. The shebang is used to run the python interpreter when the script is run as an executable.

The file extension is there for two reasons.

Firstly, it conveys information about the contents of the file. For one example, a text editor might use the file extension to recognise the script as python and highlight the syntax appropriately. Aditionally, a user can make a reasonable assumption that the file is a python script without having to open it.

Secondly, the script can be imported into another python script and used as an API. 

e.g.

    import stream2chromecast

    stream2chromecast.list_devices()
    

It is possible to register the .py file extension to be run with the python interpreter on Linux, using the binfmt-misc registry. However, I don't think that it's very common to do that.

regards,

Pat
