### ISSUE TITLE
Playback of DTS audio not working

### ISSUE THREAD

**Issue by appelflap** [Pat-Carter/stream2chromecast#28]
Maybe not a problem in stream2chromecast as such. But more like a feature to recognize other audio streams and dealing with them. Does anybody have an idea why this file does not have audio on chromecast even though it gets handled by ffmpeg?

This file works like a charm (avconv output):
`Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)`

But with this one the audio does not work:
`Stream #0:0(eng): Video: h264 (High), yuv420p, 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)`

They are both seen as video/x-matroska by the script. First tried to add transcodeopts parameters to change the audio on the fly:
`./stream2chromecast.py -transcoder ffmpeg -transcodeopts '-c:v copy -c:a ac3' /path/to/file.mkv`

I also tried to transcode it beforehand and then stream it with stream2chromecast. But the resulting file does not start on the chromecast. It looks like it keeps buffering. The command line says 'sending file'
`avconv -i /path/to/file/in.mkv -c:v copy -c:a ac3 /path/to/file/out.mkv`

**Comment by appelflap** [comment]
Ahh.. ok, forgot -transcode option. But then only the audio is working (ac3). The video does not. Tried codec copy and h264

**Comment by Pat-Carter** [comment]
Did you try just a straight transcode without any additional options? I think the default setting should transcode to a format acceptable to the Chromecast. 

i.e. 
./stream2chromecast.py -transcode /path/to/file.mkv

Also, I don't know if it was just a typo, but I notice that you didn't actually specify -transcode in your example, just -transcoder and -transcodeopts.

cheers,

Pat

**Comment by appelflap** [comment]
Using -transcode, without transcoderopts gives:
`[libvo_aacenc @ 0x24c9580] Unable to set encoding parameters
Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height`

**Comment by Pat-Carter** [comment]
I don't think I have any files with DTS audio...

This page looks like it might be a similar issue.

http://superuser.com/questions/639983/avconv-cant-convert-stream-to-mp4-file-fails-with-unable-to-set-encoding-para

Maybe the -ac 2 option might work?

**Comment by appelflap** [comment]
Not transcoding it gives video without sound.
Transcoding it with with audio to ac3 (`-transcoder ffmpeg -transcode -transcodeopts '-c:v copy -c:a ac3'`) results in sound without video. Just tried to add -ac 2, but that does not change it. I will keep searching.

**Comment by Pat-Carter** [comment]
One more thought. When you tried transcoding it beforehand and the resulting file didn't play, did you give it a fragment duration?

I think that ffmpeg / avconv mp4 output is not streamable by default.

Maybe something like:-

avconv -i /path/to/file/in.mkv -ac 2 -f mp4 -frag_duration 3000 /path/to/file/out.mkv

**Comment by appelflap** [comment]
Did not use fragment duration the first time. Tried it again now. First with your command example. But that gave some errors. 

This command worked. Have to run stream2chromecast without the `-transcode` flag to have a good result on the chromecast.
`ffmpeg -i /path/to/file/in.mkv -c:v copy -c:a ac3 -frag_duration 3000 /path/to/file/out.mkv` 

So thanks! That works. Tried some combinations of the commands to make it work without transcoding first. But maybe I'll just make a script that pre-transcodes all content that has DTS.

**Comment by appelflap** [comment]
Just a small piece of bash code for (periodically) transcoding all DTS mkv files in some dirs.
Tested it a bit, works for me, but no guarantees. Old files are kept. But you can change it to rm them.

```
#!/bin/bash

# Set the separator char to newline
IFS=$'\n'

# Loop through dirs recursively
for i in /path/to/dir1 /path/to/dir2; do
  echo "Now searching in dir $i"
  # Search for mkv files, but not the already transcoded ac3.mkv files
  for FILE in $(find $i/ -type f -name "*.mkv" | grep -v 'ac3.mkv'); do
    TOFILE=$(echo "$FILE" | sed 's/mkv$/ac3.mkv/')
    # Search for DTS audio stream in file
    FOUND=$(ffmpeg -i "$FILE" 2>&1 | grep 'Audio: dts' | head -n 1)

    if [ ! -z "$FOUND" ]; then
      if [ ! -f "$TOFILE" ];then
        echo -e "$FILE \e[91mhas DTS and needs to be transcoded\e[0m"
        echo "FOUND: $FOUND"
        # Transcode and rename old file if successful
        ffmpeg -i "$FILE" -c:v copy -c:a ac3 -frag_duration 3000 $TOFILE 2>/dev/null && mv -- "$FILE" "$FILE.old"
      else
        echo "$TOFILE already exists. Not transcoding"
      fi
    #else
      # echo "No DTS audio layer found in file"
    fi
  done
done
```

**Comment by appelflap** [comment]
Found same problem with eac3 audio layers. possible to change above script grep line:
`FOUND=$(ffmpeg -i "$FILE" 2>&1 | grep 'Audio: dts' | head -n 1)`
to
`FOUND=$(ffmpeg -i "$FILE" 2>&1 | grep -E 'Audio: (dts|eac3)' | head -n 1)`

**Comment by eduardohenriquearnold** [comment]
Instead of converting all files to DTS, I would suggest using an online transcoding procedure, as indicated by https://github.com/Pat-Carter/stream2chromecast/pull/40
