### ISSUE TITLE
pause/continue doesn't work with alt device

### ISSUE THREAD

**Issue by jp31415926** [Pat-Carter/stream2chromecast#30]
The following pauses a playing video, but does not pause it:
play video in one terminal, then in another terminal, I type:

$ ./stream2chromecast.py -pause
searching the network for a Chromecast device
device name: Living Room
[video is paused]

$ ./stream2chromecast.py -continue
searching the network for a Chromecast device
device name: Media Room
No media player app running
[video does not continue]

$ ./stream2chromecast.py -devicename "Living Room" -continue
Device name response: Living Room
found device in cache: Living Room
device name: Living Room
[video does not continue]

$ ./stream2chromecast.py -devicename 192.168.99.130 -continue
ip_addr: 192.168.99.130 device name: Living Room
[video does not continue]

**Comment by Pat-Carter** [comment]
HI,

Was the video being played with the -transcode option?  Pause / Continue doesn't work with the -transcode option at the moment.

cheers,

Pat

**Comment by jp31415926** [comment]
Yes.
