### ISSUE TITLE
Error when playing back stream

### ISSUE THREAD

**Issue by rgcosma** [Pat-Carter/stream2chromecast#32]
Hi! I'm trying to use this with a HTTPS URL that requires authentication in the form of ./stream2chromecast.py -playurl 'https://user:pass@host.domain:port/resource' and it fails with 
socket.gaierror: [Errno -2] Name or service not known
but the hostname is definitely valid, the URL works with VLC
full error is
```Stream2Chromecast version:0.6.3

Traceback (most recent call last):
  File "./stream2chromecast.py", line 755, in <module>
    run()
  File "./stream2chromecast.py", line 744, in run
    playurl(arg2, device_name=device_name)
  File "./stream2chromecast.py", line 552, in playurl
    conn.request("HEAD", path)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1242, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
```
Any hints on how to debug?

**Comment by Pat-Carter** [comment]
Hi,

The playurl option was really only added as a debugging tool.

It only really works under the scenario that:-

1. The URL points to a downloadable complete file, ie. not a internet stream.
2. The server provides a valid content-type
3. The server responds to an HTTP HEAD request
4. The file is in a format playable directly by the Chromecast.

The script initially performs an HTTP HEAD request to get the content-type in order to pass that to the Chromecast. This appears to be where it is failing on your request.

I'll have a look into adding an option that allows the specification of the content-type manually, then we can bypass the HEAD request. Then it will be down to whether the Chromecast can handle that form of URL.

In the meantime. if you have the latest version of Stream2Chromecast, you might find that the transcode option works better in this case.

Could you try this form, please and let me know how that goes?

python stream2chromecast.py -transcode https://user:pass@host.domain:port/resource

cheers,

Pat

**Comment by rgcosma** [comment]
Hi! Checked out the latest master and got a bit further:

```
$ ./stream2chromecast.py -transcode https...
avconv version 11.8-6:11.8-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  8 2016 02:37:00 with gcc 4.9.2 (Raspbian 4.9.2-10)
unable to find ffmpeg - using avconv
local ip address: 192.168.1.105
URL & content-type:  https... video/mp4
loading media...
192.168.1.101 - - [08/Nov/2016 19:34:59] "GET /?https... HTTP/1.1" 200 -
sending data
[mpeg2video @ 0x1864d40] Invalid frame dimensions 0x0.
    Last message repeated 1 times
encoder 'aac' is experimental and might produce bad results.
Add '-strict experimental' if you want to use it.
```

A broken image does appear on the Chromecast for a couple seconds, then disconnect.
This happens on a Raspberry Pi running Debian Jessie, everything as up to date as possible. The fact that it's a raspi might be a problem itself of course. Sadly there's no ffmpeg for it, and the armhf package from debian-multimedia crashes immediately with 'illegal instruction'.
The stream is quite standards compliant I am told, and VLC (on my laptop) identifies it as MPEG-1/2(mpgv), 720x576, 25fps, audio mpga, 44kHz, 256kb/s. It's definitely not video/mp4 as seems to be implied by that header message.

**Comment by Pat-Carter** [comment]
OK. What happens if you download the file from your browser or using wget?

Can you play the downloaded file directly using stream2chromecast?

**Comment by rgcosma** [comment]
Update: seems raspi is to blame (sadly, because that's what I bought it for). 
stream2chromecast installed on my Mac (with ffmpeg from brew) works with exactly the same streams and parameters. it still outputs
```
[mpeg2video @ 0x7fa79a80fc00] Invalid frame dimensions 0x0.
    Last message repeated 16 times
```
But other than that the streams work fine. Not sure if you're interested in debugging raspi itself, so for now thank you!

**Comment by Pat-Carter** [comment]
I'll have a go with the pi at some point. 
Maybe it's avconv that is having problems. There is a precompiled ffmpeg available here:-

https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian

I haven't tried it myself, but it might be worth a go?

**Comment by rgcosma** [comment]
Cool, this ffmpeg doesn't crash
```
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --prefix=/usr --enable-gpl --enable-libx264 --enable-nonfree --enable-shared --disable-static
```
sadly the raspi shows its limits: when trying with curl -o afile.mpg https... and then ./stream2chromecast.py ./afile.mpg the Chromecast doesn't like the format
```
Unsupported codec with id 94215 for input stream 2
```
when adding -transcode, it does output, with a lot of frames lost, and the CPU maxed
Seems it simply can't do mpeg2->mp4 fast enough. 
For readily-formatted mp4 streams though, like http://www.sample-videos.com/index.php#sample-mp4-video stream2chromecast -playurl works! Nice!

**Comment by Pat-Carter** [comment]
I don't think the Chromecast itself will play mpeg2 files. e.g. like DVDs

That was why I added the transcode function in the first place.

You could try adjusting the video and audio bitrates from the transcoder though:-

./stream2chromecast.py -transcodeopts '-b:v 1000k -b:a 128k' -transcode afile.mpg

...the default is 2000k for the video, so that should half it to 1000k. It might make it run a bit more smoothly.

**Comment by rgcosma** [comment]
It does improve a bit, but only just; the raspi CPU is too slow, and doesn't have any of those useful Intel instructions:
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls
Its GPU is capable of full-HD, but don't know if it can be used by userland apps and I think the driver is closed source?

**Comment by Pat-Carter** [comment]
It is asking quite a lot of a small processor.

I don't know whether it would help the transcoder in this case, but the raspberry pi is capable of hardware decoding mpeg2 files. You just have to install a license key file.

They cost £2.40 from the raspberry pi store:-

http://www.raspberrypi.com/mpeg-2-license-key/

**Comment by rgcosma** [comment]
OK, update after
1. Investing 2 pounds in the MPEG license :)
2. Rebuilding ffmpeg from the latest git with ./configure --enable-mmal --enable-omx-rpi --enable-omx --enable-openssl so that it uses OpenMAX
stream2chromecast does work correctly, and visibly faster than before, but not enough.
My video path would be MPEG2->HTTPS->raspi->MP4->Chromecast.
Asking the small thing to do both simultaneously is just too much and it only gets a couple FPS.

**Comment by rgcosma** [comment]
Hi! Just in case someone reads this thread, the raspi 3 can do it :)
ffmpeg is 
./configure --enable-mmal --enable-omx-rpi --enable-omx --enable-openssl --enable-shared --enable-pthreads --enable-gpl --enable-nonfree --enable-hardcoded-tables --enable-avresample --enable-libmp3lame --enable-libx264 --enable-libxvid
Also bought the license for MPEG2.
Invocation in stream2chromecast.py is
-c:a libmp3lame -b:a 128k -c:v h264_omx -b:v 3192k -threads 3
Also stream2chromecast didn't quite cope with my HTTPS streams, losing connection very often (I'd blame urllib for that) so I ended up also running Apache as reverse proxy and letting it handle reconnection, authentication and decryption
<VirtualHost *:80>
SSLProxyEngine On
RequestHeader set Authorization "Basic blahblah"
RequestHeader edit Host ^host.domain host.domain
ProxyPass "/resource" "https://host.domain:port/resource" nocanon
ProxyPassReverse "/resource" "https://host.domain:port/resource"
</VirtualHost>
And stream2chromecast.py -transcode http://localhost/resource
The raspi's loadavg is now around 2-3 depending on source bitrate.
