### ISSUE TITLE
script not resilient to losing access to the movie file during playback

### ISSUE THREAD

**Issue by Aranjedeath** [Pat-Carter/stream2chromecast#34]
something with linux forces my external drive to be unmounted (and automatically remounted) at random, interrupting playback. There is seemingly no way to recover from this. I can't find a seek or continue-from-last-time command (how -continue works is completely unclear, do I run the script twice? but it doesn't matter, as I was -transcode'ing)

Any help that can be provided (or feature impetus) is much appreciated.

**Comment by Pat-Carter** [comment]
I'm afraid there's no "continue from last time" option.

The continue option is essentially "unpause". Pausing doesn't work with transcode.

The problem with a "continue from last time" function is that we would have to watch the status of every playback session and store the playback position reported by the Chromecast. The Chromecast caches a portion of the media so, we would have to poll the device and save how far it had got with the playback or each file.

Then, assuming we had done that, transcode supports seeking to a time positon, but raw untranscoded playback just serves the file as a binary. We would have to be able to figure out which byte offset in the media file corresponds to the seek time position and serve it from there.

Perhaps as a workaround, you could do one of the following.

1. use the transcode seek option to resume playback e.g.:-

stream2chromecast.py -transcodeinputopts '-ss 00:15:00' -transcode the_file.mp4

2. copy the file to your main drive before playback.
