### ISSUE TITLE
Support for multiroom(chromecast audio group)

### ISSUE THREAD

**Issue by bobo71dream** [Pat-Carter/stream2chromecast#35]
Hi.

Is it possible to add a group of chromecast audio´s to play music?

best regards...

**Comment by Pat-Carter** [comment]
Hi,

I don't think so - at least not as far as the current options go. I've only got one first gen Chromecast.

Were you looking for simultaneous playback from more than one device at the same time?

cheers,

Pat

**Comment by bobo71dream** [comment]
My goal is to use the my linux server for streaming audio to multiple chromecats audio (offical name is Multi-room group playback)

see here: https://support.google.com/chromecast/answer/6329016?hl=en

**Comment by Pat-Carter** [comment]
Ah - OK.

No, sorry - it doesn't look like it:-

>  Can I add my Chromecast (that casts video) or Android TV to a group?
No, grouping Chromecast (that casts video) or Android TVs is not supported.

**Comment by Pat-Carter** [comment]
it might be worth checking out https://github.com/balloob/pychromecast if you haven't already.

**Comment by bobo71dream** [comment]
Yes.  know pychromecast. But my Server ist a embeded system. I am Not able to  running  protobuf... :-(.
