### ISSUE TITLE
Other devices that chromecast detected

### ISSUE THREAD

**Issue by bigon** [Pat-Carter/stream2chromecast#38]
Hi,

I've on my network an IPTV box from my provider and stream2chromecast detects it and tries to use it.

The problem is that it will then try to play stream a video to it, but it's obviously not working

**Comment by Pat-Carter** [comment]
Hi,
The devicename parameter should allow you to specify the device by name.
Cheers,
Pat

**Comment by bigon** [comment]
Yeah indeed, but shouldn't stream2chromecast only detect chromecast?

**Comment by Pat-Carter** [comment]
It is not designed to be limited to chromecasts.
