### ISSUE TITLE
No Chromecast Device Found While on VPN

### ISSUE THREAD

**Issue by Moosheplusplus** [Pat-Carter/stream2chromecast#45]
Currently I've noticed that while using a VPN (connected via PPTP), no devices could be found. I'm able to discover devices by disabling the VPN and everything works fine, but as soon as I enable the VPN connection again, it will not discover any devices.

With VPN connected:
```
$ stream2chromecast -devicelist
Searching for devices, please wait...
0 devices found
```

With no VPN connected:
```
$ stream2chromecast -status
searching the network for a Chromecast device
device name: Chromecast
{'applications': [{'statusText': u'YouTube TV', 'displayName': u'YouTube', 'appId': u'233637DE'}], 'host': '192.168.1.219', 'client': ('192.168.1.218', 48208), 'media_status': None, 'receiver_status': None}
```

**Comment by Pat-Carter** [comment]
It looks like your device is not reachable from your VPN.

**Comment by Moosheplusplus** [comment]
The device is reachable even when connected to the VPN, because I've been able to stream youtube through the Chrome web browser. I only seem to have an issue with discovering the Google Chromecast through stream2chromecast while connected through a VPN.

**Comment by Pat-Carter** [comment]
OK - it must be a limitation of discovery then. Sorry.

**Comment by ericvrp** [comment]
Can this be worked around. I am having a similar problem. When I am on VPN the Chromecast in my local network are no longer found.

**Comment by Pat-Carter** [comment]
I don't think so, you have to be on the same network as the Chromecast.

**Comment by ericvrp** [comment]
But I am. As far as I know VPN is only for connections out of my local network. Anyway. My distro updated strean2chromecast and it is found now. So perhaps something also was going on.

**Comment by Pat-Carter** [comment]
OK. That's good. :-)
