### ISSUE TITLE
Can not stream if another device is already connected to Chromecast

### ISSUE THREAD

**Issue by linnit** [Pat-Carter/stream2chromecast#46]
If another device has/is streaming something to the Chromecast and I try and run ./stream2chromecast.py it just appears to sleep.

I need to explicitly stop the other device from streaming and then run ./stream2chromecast.py

**Comment by Pat-Carter** [comment]
It seems to work OK for me, both when stream2chromecast interrupts another stream2chromecast and also when it interrupts my mobile casting youtube.

**Comment by linnit** [comment]
Hm, I'll do a bit more testing and see if I can figure out what my issue is.
