### ISSUE TITLE
Add support to transcode using accelerated playback

### ISSUE THREAD

**Issue by jsalatiel** [Pat-Carter/stream2chromecast#5]
It would be very nice if stream2chromecast would be able to use ffpmpeg to transcode using 1,5x or 2x speed.

**Comment by Pat-Carter** [comment]
Hi.

I can have a look into that.

What should the audio do in that case?

Pat

**Comment by jsalatiel** [comment]
audio will be synced too
Sorry , i forgot to send the commands =)
add this filter to ffmpeg ( i havent test on avconf )

-filter_complex "[0:v]setpts=0.666666667*PTS[v];[0:a]atempo=1.5[a]"   -> 1,5x
-filter_complex "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2[a]"   -> 2x

Basically setPTS parameter will be 1/SPEED_MULTIPLIER , and atempo parameter will be SPEED_MULTIPLIER.

I have already tested changing the stream2chromecast line below:
FFMPEG = 'ffmpeg -i "%s" -preset %s -c:a libfdk_aac -f mp4 -frag_duration 3600 -b:v %s  -filter_complex "[0:v]setpts=0.666666667*PTS[v];[0:a]atempo=1.5[a]"  -map "[v]" -map "[a]" -'

but it will only works for 1,5x

**Comment by Pat-Carter** [comment]
OK - thanks.

I'm going to be committing some more updates this week. 

I'll see if I can do something about this one next.

**Comment by Pat-Carter** [comment]
I've added a general purpose "-transcodeopts" parameter to provide a means to pass in custom ffmpeg/avconv parameters.

e.g. 
stream2chromecast.py -transcodeopts '-filter_complex "[0:v]setpts=0.666666667*PTS[v];[0:a]atempo=1.5[a]" -map "[v]" -map "[a]" '  -transcode my-file.mpg
