### ISSUE TITLE
Add suport to transcode with subtitles

### ISSUE THREAD

**Issue by jsalatiel** [Pat-Carter/stream2chromecast#6]
It would be nice if we could transcode with subtitles. Currently no application ( even on android ) is able to send subtitles to chromecast =)

**Comment by Pat-Carter** [comment]
OK. 

How about if we add a general purpose parameter to pass additional options to ffmpeg / avconv when transcoding?

Something like:-

stream2chromecast.py -transcode -transcoder-options "<options>" myfile.mp4

**Comment by jsalatiel** [comment]
Hi paul, i actually was thinking about making easy for the end user. I have no problems to add advanced command-line options, but several people would enjoy an easier way.
Basically i only see two features missing ( final user perspective ) in this application.
Accelerated playback and subtitles =)

btw, subtitles is just add '-vf subtitiles="subtitle.srt"'

But it is just an option, for me the general purpose parameter will work just fine =)

**Comment by jsalatiel** [comment]
but ofcourse a general purpose parameter would also be nice

**Comment by Pat-Carter** [comment]
OK. I'll take a look at these during the week.

I'm putting in some changes to simplify the transcoding side of things anyway, so we should be able to do something.

:-)

**Comment by jsalatiel** [comment]
To make things simpler, in case of subtitles, if the user enable transcode, you could check directly if there's a subtitle with the same name of the video in the same directory ( srt extension) and enable it

**Comment by yannski** [comment]
There's also the case of Matroska file where subtitle are already embedded into the file.

**Comment by Pat-Carter** [comment]
I've added a general purpose "-transcodeopts" parameter to provide a means to pass in custom ffmpeg/avconv parameters.
