### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by ao-il** [Pat-Carter/stream2chromecast#66]
Stream2chromecast has stopped working. It finds the device and then hangs afterwards. Please help.

**Comment by Go3Team** [comment]
It's stopped working on my end too.  I have it on 2 machines, 1 is Ubuntu 14.04, the other 16.04.  Both machines were recently updated.

**Comment by ao-il** [comment]
@Go3Team thanks for confirming this. I guess python 2 is broken in the recent updates? Other apps are working including pychromecast (python 3).

**Comment by Pat-Carter** [comment]
I've just tried it on my machine (Ubuntu 14.04) and it still seems to work OK for me. 

To be fair, I don't use the chromecast very much these days - (I've put a Raspberry Pi in my last available HDMI socket) - but I fished out the Chromecast, ran an apt-get upgrade and tested and all seems OK. 

Any chance of some detail on what you ran and the options... transcode etc... maybe the command line and the output?

**Comment by ao-il** [comment]
Did you run `apt-get update` `before apt-get upgrade`? Maybe it doesn't matter. This is my output..
`$ stream2chromecast.py -status
searching the network for a Chromecast device
device name: ChromecastAudio-NAD

`

**Comment by ao-il** [comment]
Because it gets stuck there, I used ctrl-c to cancel and this is what it outputs..
CTraceback (most recent call last):
  File "/usr/bin/stream2chromecast.py", line 540, in <module>
    run()
  File "/usr/bin/stream2chromecast.py", line 514, in run
    get_status(device_name=device_name)
  File "/usr/bin/stream2chromecast.py", line 358, in get_status
    print CCMediaController(device_name=device_name).get_status()
  File "/usr/share/stream2chromecast/cc_media_controller.py", line 376, in get_status
    self.get_receiver_status()
  File "/usr/share/stream2chromecast/cc_media_controller.py", line 241, in get_receiver_status
    self.send_msg_with_response(namespace, data)
  File "/usr/share/stream2chromecast/cc_media_controller.py", line 187, in send_msg_with_response
    return self.get_response(self.request_id)
  File "/usr/share/stream2chromecast/cc_media_controller.py", line 151, in get_response
    msg = self.read_message()
  File "/usr/share/stream2chromecast/cc_media_controller.py", line 121, in read_message
    data += self.sock.recv(4)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
KeyboardInterrupt

**Comment by Pat-Carter** [comment]
OK - I think I know what's wrong. I'll push the fix over the weekend.

**Comment by ao-il** [comment]
OK, Thanks.

**Comment by Pat-Carter** [comment]
OK -  I've pushed a change to cc_message.py. 

Hoping that will fix the issue.

**Comment by ao-il** [comment]
Works Now! Thanks a lot.

**Comment by Pat-Carter** [comment]
Glad it worked. Cheers!

**Comment by Go3Team** [comment]
Working here as well, thanks!
