### ISSUE TITLE
Stopped working again after firmware update

### ISSUE THREAD

**Issue by ao-il** [Pat-Carter/stream2chromecast#70]
stream2chromecast has stopped working after Google's firmware update. Prints "No Chromecast found on network" and exits. I think the issue is similar to #66, except that it is with cc_device_finder.py this time. Please help. Thanks in advance!

**Comment by ao-il** [comment]
`$stream2chromecast -status` fails, but `$stream2chromecast -devicename <ip> -status` works. Can anyone confirm this?

**Comment by Carter90** [comment]
I get the the broken behavior.
I'm running a Chromecast audio, firmware version: 1.28.100555

Ubuntu 16.04 64 bit
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -devicename 192.168.1.234 -status
ip_addr: 192.168.1.234 device name: 
{'applications': [], 'host': '192.168.1.234', 'client': ('192.168.1.211', 4948#), 'media_status': None, 'receiver_status': None}

--------------------------------------------------------------------------------------------------------------------------------------
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -status
searching the network for a Chromecast device
No Chromecast found on the network

When I'm steaming to it
--------------------------------------------------------------------------------------------------------------------------------------
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -devicename 192.168.1.234 -status
ip_addr: 192.168.1.234 device name: 
{'applications': [{'statusText': u'Now Casting', 'displayName': u'Default Media Receiver', 'appId': u'CC1AD845'}], 'host': '192.168.1.234', 'client': ('192.168.1.211', 4957#), 'media_status': {u'mediaSessionId': 1, u'supportedMediaCommands': 15, u'currentTime': 2.466253, u'media': {u'duration': None, u'contentId': u'http://ice1.somafm.com/thistle-128-mp3', u'streamType': u'buffered', u'contentType': u'audio/mpeg'}, u'playbackRate': 1, u'volume': {u'muted': False, u'level': 1}, u'repeatMode': u'REPEAT_OFF', u'currentItemId': 1, u'items': [{u'itemId': 1, u'media': {u'duration': None, u'contentId': u'http://ice1.somafm.com/thistle-128-mp3', u'streamType': u'buffered', u'contentType': u'audio/mpeg'}, u'customData': {u'payload': {u'title:': u''}}, u'autoplay': True}], u'playerState': u'PLAYING'}, 'receiver_status': {u'displayName': u'Default Media Receiver', u'statusText': u'Now Casting', u'transportId': u'c85882e7-a639-425e-a51f-a07b3fa89eea', u'isIdleScreen': False, u'launchedFromCloud': False, u'sessionId': u'c85882e7-a639-425e-a51f-a07b3fa89eea', u'namespaces': [{u'name': u'urn:x-cast:com.google.cast.debugoverlay'}, {u'name': u'urn:x-cast:com.google.cast.broadcast'}, {u'name': u'urn:x-cast:com.google.cast.media'}], u'appId': u'CC1AD845'}}

--------------------------------------------------------------------------------------------------------------------------------------
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -status
searching the network for a Chromecast device
No Chromecast found on the network

**Comment by ao-il** [comment]
Thanks @Carter90 for confirming this issue. My guess is that cc_device_finder is broken. Some things must have been hardcoded, as other apps are still working even after the update. Last update broke cc_messages. Let's see what will break next.

**Comment by Carter90** [comment]
firmware version: 1.23.84839
to
firmware version: 1.28.100555

I just tested it on my 1st Gen Chromecast running firmware version: 1.23.84839 and it discovers it fine, I then upgraded the firmware to firmware version: 1.28.100555, rebooted my laptop and was still able to discover. 

If I have time I would do a factory restore on my audio chromecast and do the same test because the 1st Gen seems unaffected for me.

----------------------------------------------------------------------------------------
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -status
searching the network for a Chromecast device
device name: Dining Room TV
{'applications': [{'statusText': u'', 'displayName': u'Backdrop', 'appId': u'E8C28D3C'}], 'host': '192.168.1.221', 'client': ('192.168.1.211', 47786), 'media_status': None, 'receiver_status': None} 

After firmware upgrade
----------------------------------------------------------------------------------------
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -status
searching the network for a Chromecast device
device name: Dining Room TV
{'applications': [{'statusText': u'', 'displayName': u'Backdrop', 'appId': u'E8C28D3C'}], 'host': '192.168.1.221', 'client': ('192.168.1.211', 54034), 'media_status': None, 'receiver_status': None}

**Comment by ao-il** [comment]
I have just done a factory reset and it does fix it.

**Comment by Carter90** [comment]
Yeah, I just tried a factory reset It does not rollback the firmware so I guess I cant easily test that.

**Comment by Pat-Carter** [comment]
Could you take a look at the output from... 

http://<chromecast-ip>:8008/ssdp/device-desc.xml

and...

http://<chromecast-ip>:8008/setup/eureka_info?options=detail

please.

I only have a first gen chromecast to test against.

**Comment by ao-il** [comment]
Yes, the device automatically updates to the latest version.

**Comment by Carter90** [comment]
@Pat-Carter 
On the audio chromecast 

http://192.168.1.234:8008/ssdp/device-desc.xml
```
This 192.168.1.234 page can’t be found

No webpage was found for the web address: http://192.168.1.234:8008/ssdp/device-desc.xml
HTTP ERROR 404
```

http://192.168.1.234:8008/setup/eureka_info?options=detail
```
{"bssid":"","build_version":"100555","cast_build_revision":"1.28.100555","closed_caption":{},"connected":true,"detail":{"icon_list":[{"depth":32,"height":55,"mimetype":"image/png","url":"/setup/icon.png","width":98}],"locale":{"display_string":"English (United States)"},"manufacturer":"Google Inc.","model_name":"Chromecast Audio","timezone":{"display_string":"Pacific Standard Time (Los Angeles)","offset":-480}},"ethernet_connected":true,"has_update":false,"hotspot_bssid":"FA:8F:CA:95:D9:84","ip_address":"192.168.1.234","locale":"en-US","location":{"country_code":"US","latitude":255.0,"longitude":255.0},"mac_address":"A4:77:33:FB:B3:08","name":"Carters Bedroom","opt_in":{"crash":true,"location":false,"opencast":false,"stats":true},"public_key":"MIIBCgKCAQEAuV1WthXDetMHR0cvHderk0roHI+N36AGXEZv/GKe3yNvCZldc40k2AT50Y5MWjXrg0qUzYwrusUrqkpFtZN0MmSQtW26RSxKJza0nlbSasVMENxuQMAh4fJgWQRQQwPuZ/VlghCOS4xCL02F/TQOglM+471OSprOKeolw4RoIWB2K4tqRFLwJYgQG4IhOxjNRhjnL58YoP/U759EQwhq0xCdUqOoOWfnwQu22i74vkI/pFd54ltcsmFSCeHVi/MEclB2jxXwvAjh2r9moJNQMAohUE5Upb02V2a5wKF6PXxOhjoHZ4qxDimxWVwiKvW/yB07Vg9Snzw0nA18s6kK0QIDAQAB","release_track":"stable-channel","setup_state":60,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":0,"num_connect_wifi":0,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":0,"num_obtain_ip":0},"ssdp_udn":"6a58daec-4626-d939-6ceb-cab2762ae1ee","ssid":"CabrilloTestvirusnetwork","time_format":1,"timezone":"America/Los_Angeles","tos_accepted":true,"uma_client_id":"68c88064-0adb-460d-8c0e-49ba6ba07df6","uptime":733.26,"version":8,"wpa_configured":true,"wpa_id":0,"wpa_state":1}
```

**Comment by Pat-Carter** [comment]
it looks like github has choked on my message...

Could you take a look at the output from...

http://(chromecast-ip-addr):8008/ssdp/device-desc.xml

and...

http://(chromecast-ip-addr):8008/setup/eureka_info?options=detail

please. - against the IP address of your chromecasts.

I only have a first gen chromecast to test against.

**Comment by Pat-Carter** [comment]
Thanks Carter - and I guess on the first-gen one, both requests work OK?

**Comment by Carter90** [comment]
@Pat-Carter right
First Gen
http://192.168.1.221:8008/ssdp/device-desc.xml
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.221:8008</URLBase>
<device>
<deviceType>urn:dial-multiscreen-org:device:dial:1</deviceType>
<friendlyName>Dining Room TV</friendlyName>
<manufacturer>Google Inc.</manufacturer>
<modelName>Eureka Dongle</modelName>
<UDN>uuid:824845de-5d8d-03ff-187f-06eaee3f77ca</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>98</width>
<height>55</height>
<depth>32</depth>
<url>/setup/icon.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
<serviceId>urn:dial-multiscreen-org:serviceId:dial</serviceId>
<controlURL>/ssdp/notfound</controlURL>
<eventSubURL>/ssdp/notfound</eventSubURL>
<SCPDURL>/ssdp/notfound</SCPDURL>
</service>
</serviceList>
</device>
</root>
```
http://192.168.1.221:8008/setup/eureka_info?options=detail
```
{"bssid":"2c:4d:54:6e:13:e2","build_version":"100555","cast_build_revision":"1.28.100555","closed_caption":{},"connected":true,"detail":{"icon_list":[{"depth":32,"height":55,"mimetype":"image/png","url":"/setup/icon.png","width":98}],"locale":{"display_string":"English (United States)"},"manufacturer":"Google Inc.","model_name":"Eureka Dongle","timezone":{"display_string":"Pacific Standard Time (Los Angeles)","offset":-480}},"ethernet_connected":false,"has_update":false,"hotspot_bssid":"FA:8F:CA:81:5C:F5","ip_address":"192.168.1.221","locale":"en-US","location":{"country_code":"US","latitude":255.0,"longitude":255.0},"mac_address":"6C:AD:F8:28:37:3D","name":"Dining Room TV","noise_level":-87,"opt_in":{"crash":true,"location":false,"opencast":false,"stats":true},"public_key":"MIIBCgKCAQEAvjeambUdKR7WZtzXY7FKLc6VoXo15l8cdUWlagJTUtwEC1+yeKjMn8IPI1YpF6DbmWWAdAgMSAuxeeUtNrNwyiWEmWFofFZMYBYznSqf8AkoeW2jxwFwwsi5Rr3muTxyaCg+7S5VQ3gBWUIMLvlmbjpKwkgGGnqB4YbRuKOFgDW4lnlnt9p7EQXikXV6LddipWjUMIjr7GS+TpynCO5AbKZGXC/lhkHyKVf/pC4PYqdyyt8CH7y5UU0Mf963/gLu+4P91pQ6W+UEBCXonbDtYehDjayF7LgogD57cRo+KhhQoGxBwEui0f5OhQkhesSJ1phMctPAY8XFxXoDEQIDAQAB","release_track":"preview-joining-stable-channel","setup_state":60,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":0,"num_connect_wifi":0,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":0,"num_obtain_ip":0},"signal_level":-64,"ssdp_udn":"824845de-5d8d-03ff-187f-06eaee3f77ca","ssid":"CabrilloTestvirusnetwork","time_format":1,"timezone":"America/Los_Angeles","tos_accepted":true,"uma_client_id":"26E9CC6B-55F5-A272-C95C-ABA182C51965","uptime":453.65,"version":8,"wpa_configured":true,"wpa_id":2,"wpa_state":10}
```

**Comment by Pat-Carter** [comment]
OK - thanks... I'll see if I can change it to check the eureka_info url instead of the old one.

**Comment by ao-il** [comment]
The (first) output is the same for me on chromecast audio.

**Comment by Pat-Carter** [comment]
Could you also try 

python stream2chromecast.py --devicelist

please?

**Comment by ao-il** [comment]
stream2chromecast -devicelist
Searching for devicese, please wait...
0 devices found

**Comment by Pat-Carter** [comment]
Could you try applying this change please...

In cc_device_finder.py, change the function  get_device_name(ip_addr)

to the following:-
```

import json                                    
def get_device_name(ip_addr):
    """ get the device friendly name for an IP address """
    
    try:
        conn = httplib.HTTPConnection(ip_addr + ":8008")
        conn.request("GET", "/ssdp/device-desc.xmlX")
        resp = conn.getresponse()
        
        if resp.status == 200:
            status_doc = resp.read()
            try:
                xml = ElementTree.fromstring(status_doc)

                device_element = xml.find("{urn:schemas-upnp-org:device-1-0}" + "device")

                return device_element.find("{urn:schemas-upnp-org:device-1-0}" + "friendlyName").text

            except ElementTree.ParseError:
                return ""    
        else:
            if resp.status == 404:
                print "status 404"
                
                conn = httplib.HTTPConnection(ip_addr + ":8008")
                conn.request("GET", "/setup/eureka_info?options=detail")
                resp = conn.getresponse()  

                if resp.status == 200:
                    status_doc = resp.read()   
                    message = json.loads(status_doc) 
                    print "name -> ", message['name']  
                    return message['name'] 
            else:
                return "" 
    except:
        # unable to get a name - this might be for many reasons 
        # e.g. a non chromecast device on the network that responded to the search
        return "" 

```

**Comment by Carter90** [comment]
With the changes
I also deleted the cc_device_finder.pyc file to make sure it regenerated and it did
Still not showing the audio chromecast 
```
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py --devicelist

-----------------------------------------

Stream2Chromecast version:0.6.3

Copyright (C) 2014-2016 Pat Carter
GNU General Public License v3.0
https://www.gnu.org/licenses/gpl-3.0.html

-----------------------------------------

searching the network for a Chromecast device
status 404
name ->  Dining Room TV
device name: Dining Room TV
media file --devicelist not found

```

**Comment by ao-il** [comment]
It is `-devicelist`. That's why it can't recognize the argument.

**Comment by Pat-Carter** [comment]
ah yes, sorry - that should gave been -devicelist with one hyphen.

**Comment by Carter90** [comment]
I turned off the first gen, the audio chromecast is on and steaming, here is the output with both arguments 

```
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py --devicelist

-----------------------------------------

Stream2Chromecast version:0.6.3

Copyright (C) 2014-2016 Pat Carter
GNU General Public License v3.0
https://www.gnu.org/licenses/gpl-3.0.html

-----------------------------------------

searching the network for a Chromecast device
No Chromecast found on the network
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -devicelist
Searching for devices, please wait...
0 devices found
```

**Comment by Pat-Carter** [comment]
OK - I guess they've stopped implementing SSDP discovery on the newer devices. 
I knew it was deprecated but it worked fine on mine (and still does).

There's some info here https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIP

I'll see if I can get mDNS working. Might take a while though - I'm a bit snowed under at the moment.

**Comment by Pat-Carter** [comment]
I've put together an mDNS query that seems to work on my device.

Could you try testing it for me please? 

(as well as the change we tried earlier)

In cc_device_finder.py, change the function search_network(device_limit=None, time_limit=5):

to the following:-

```

def search_network(device_limit=None, time_limit=5):
    """ mDNS discovery """
    
    addrs = []


    message = '\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x0b\x5f\x67\x6f\x6f\x67\x6c\x65\x63\x61\x73\x74\x04\x5f\x74\x63\x70\x05\x6c\x6f\x63\x61\x6c\x00\x00\x0c\x00\x01'
    m_addr, m_port = ('224.0.0.251', 5353)

    intf = socket.gethostbyname(socket.gethostname())
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
    sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_TTL, 255)
    sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_LOOP, 1)
    sock.bind(('', m_port))
    sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_IF, socket.inet_aton(intf) + socket.inet_aton('0.0.0.0'))
    sock.setsockopt(socket.SOL_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(m_addr) + socket.inet_aton('0.0.0.0'))

    sock.settimeout(5)


    try:
        print "Sending mDNS"
        sock.sendto(message, 0, (m_addr, m_port))    


        while True:
            print 'waiting to receive'
            try:
                data, addr = sock.recvfrom(1024)
                
                print 'received response from', addr[0]
                
                if "_googlecast\x04_tcp\x05local" in data and "md=Chromecast" in data:
                    print "is chromecast"
                    addrs.append(addr[0])
                                    
            except socket.timeout:
                print 'timed out, no more responses'
                break

    finally:
        print 'closing socket'
        sock.close()    
        
    return addrs

```

**Comment by Carter90** [comment]
Looks good dude.
That is my audio chromecast
So 192.168.1.211 is my current system, & 192.168.1.234 is my Audio Chromecast. 

```
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py --devicelist

-----------------------------------------

Stream2Chromecast version:0.6.3

Copyright (C) 2014-2016 Pat Carter
GNU General Public License v3.0
https://www.gnu.org/licenses/gpl-3.0.html

-----------------------------------------

searching the network for a Chromecast device
Sending mDNS
waiting to receive
received response from 192.168.1.211
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
timed out, no more responses
closing socket
status 404
name ->  Carters Bedroom
device name: Carters Bedroom
media file --devicelist not found
carter@CartersFarragut:~/stream2chromecast/stream2chromecast$ python stream2chromecast.py -devicelist
Searching for devices, please wait...
Sending mDNS
waiting to receive
received response from 192.168.1.211
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
timed out, no more responses
closing socket
1 devices found
192.168.1.234 : status 404
name ->  Carters Bedroom
Carters Bedroom

```

**Comment by Pat-Carter** [comment]
That's great - thanks for checking.

It's a bit of a bodge... I'll tidy it up and commit it tomorrow.

:-)

**Comment by Pat-Carter** [comment]
OK - I've pushed up a fix for SSDP having been removed. Basically what we've been testing here.

It's a it rough for the moment - mainly because I know nothing about mDNS :-)

It seems to work on my old 1st gen device.

Could you give it a go please and let me know how it goes. 

cheers,

Pat

**Comment by ao-il** [comment]
Ok, it seems to work too on my audio chromecast. Thanks a lot!

**Comment by ao-il** [comment]
Will wait for the other guy to confirm and then close this issue.

**Comment by Carter90** [comment]
It's abit verbose 
Also I am not seeing my first gen in the "device name" list but I do see it say "received response from 192.168.1.221
is chromecast" 
I don't see "Dining Room TV" anywhere in the list output. 
I am able to steam the name If I type it in like below. 

I just ordered more audios so 
```carter@CartersFarragut:~/stream2chromecast-master$ python stream2chromecast.py -list

-----------------------------------------

Stream2Chromecast version:0.6.3

Copyright (C) 2014-2016 Pat Carter
GNU General Public License v3.0
https://www.gnu.org/licenses/gpl-3.0.html

-----------------------------------------

searching the network for a Chromecast device
Sending mDNS
waiting to receive
received response from 192.168.1.211
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.234
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
timed out, no more responses
closing socket
status 404
name ->  Carters Bedroom
device name: Carters Bedroom
media file -list not found
```
I am able to stream with the names
```python stream2chromecast.py -devicename "Carters Bedroom" /home/carter/Above\ \&\ Beyond\ -\ We\'re\ All\ We\ Need.mp3

python stream2chromecast.py -devicename "Dining Room TV" /home/carter/Above\ \&\ Beyond\ -\ We\'re\ All\ We\ Need.mp3
 ```

**Comment by Carter90** [comment]
If I power down the Audio Chromecast then the first gen shows up in the list

```
carter@CartersFarragut:~/stream2chromecast-master$ python stream2chromecast.py -list

-----------------------------------------

Stream2Chromecast version:0.6.3

Copyright (C) 2014-2016 Pat Carter
GNU General Public License v3.0
https://www.gnu.org/licenses/gpl-3.0.html

-----------------------------------------

searching the network for a Chromecast device
Sending mDNS
waiting to receive
received response from 192.168.1.211
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.211
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.188
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
received response from 192.168.1.155
waiting to receive
received response from 192.168.1.221
is chromecast
waiting to receive
timed out, no more responses
closing socket
status 404
name ->  Dining Room TV
device name: Dining Room TV
media file -list not found
```

**Comment by ao-il** [comment]
It's `-devicelist` and not `-list`. Type stream2chromecast for usage. When you power off your chromecast, you should wait for the light to turn white - indicating that it's ready to cast.

**Comment by Carter90** [comment]
Much better
```
carter@CartersFarragut:~/stream2chromecast-master$ python stream2chromecast.py -devicelist 
Searching for devices, please wait...
Sending mDNS query
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
2 devices found
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
```

I was still able to get it into a funny state when I am streaming to it while listing
```
carter@CartersFarragut:~/stream2chromecast-master$ python stream2chromecast.py -devicelist 
Searching for devices, please wait...
Sending mDNS query
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
chromecast found: 192.168.1.234
chromecast found: 192.168.1.221
26 devices found
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
192.168.1.234 : Carters Bedroom
192.168.1.221 : Dining Room TV
```

**Comment by Carter90** [comment]
@ao-il Thanks for catching that 

By power off I mean I am unplugging it. 
Also I have been streaming to the devices and making sure they are discoverable by things like the Android Home app and Chrome and such, before I run the stream2chromecast

**Comment by ao-il** [comment]
Ok. I suppose your devices are now discoverable. Is it fine to close this issue?

**Comment by Carter90** [comment]
... Yeah but then you should open 2 more for the '26 devices found' error and the invalid command line arg.

**Comment by ao-il** [comment]
Ok sorry, didn't see the duplicates.

**Comment by Pat-Carter** [comment]
okey dokey - I've just pushed an update to the device finder code to only add each IP address once.

It looks like it can send back multiple responses to a query. For some reason, it appears to do this more frequently when a file is being streamed. Well spotted!

cheers,

Pat

**Comment by Carter90** [comment]
@Pat-Carter  Looks good, just got 2 more audio Chromecasts and tested by steaming to 2 of them and running devicelist.  
Thanks for all your hard work Pat. 
```
carter@CartersFarragut:~/stream2chromecast-master$ python stream2chromecast.py -devicelist 
Searching for devices, please wait...
Sending mDNS query
chromecast found: 192.168.1.234
chromecast found: 192.168.1.223
chromecast found: 192.168.1.221
chromecast found: 192.168.1.224
4 devices found
192.168.1.234 : Carters Bedroom
192.168.1.223 : Barn speaker
192.168.1.221 : Dining Room TV
192.168.1.224 : Living Room speaker
```
